raise an explicit exception when response does not include a JSON body
There should be no reason for the API to respond with a `200 OK` and an empty body, however, sometimes that has happened to us, resulting in this exception:

```
NoMethodError: undefined method `[]' for nil
```

This comes from:

* `nylas/handler/api_operations.rb` in `get_list` at line `34`
* `nylas/resources/messages.rb` in `list` at line `31`

Instead of raising a `NoMethodError` when trying to access `response`, `parse_response` now explicitly checks that it's returning *something*.